# -*- coding: utf-8 -*-
"""PA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUI-xQGipG6u6pO7gxlxxFAhWsl62k1G

Aula 01
"""

# input Num
idade = 25
print(idade)
altura = 1.78
numero_complexo = 2 + 3
# text
nome = 'Lucas Lindinho'
#bool
esta_chovendo = False
#

"""Aula 02

Algortimo de calcula o quadrado

#Entrada

Ler o Dado

#Processamento

multiplica o lado pelo lado

#Saida

Mostrar Resultado
"""

# Entrada
lado = 6

# Processamento
quadrado = lado * lado

# Saida
print(f"total da area dos quadrados:{quadrado}")

"""Aula 03"""

Tamanho = float(input("digite o tamanho da sala em metros: "))
comprimento = float(input("digite o comprimento da sala em metros: "))
area = Tamanho * comprimento
print(f"a area da sala é: {area}m²")

"""Escrever um algoritimo e o programa que recebe 04 notas e calcula a media dos alunos e exibe a media"""

n1 = float(input("digite a primeira nota: "))
n2 = float(input("digite a segunda nota: "))
n3 = float(input("digite a terceira nota: "))
n4 = float(input("digite a quarta nota: "))
md = (n1 + n2 + n3 + n4) / 4
print(f"a media do aluno é: {md}")

num = float(input("digite um numero: "))
dob = num * 2
print(f"O Dobro do número selecionado é: {dob}")

# Entrada
comprimento = float (input("digite o comprimento: "))
altura = float (input("digite o valor da altura: ") )

# Processamento
area = comprimento * altura

# Saida
print(f"AREA DA SALA É: {area} metros quadrados")

# Fazer um cadastro de usuário simples.
# Entrada: nome e idade

# Processamento : armazenar os dados

# Saida: Mensagem de boas vindas

# Entrada

nome = str (input("digite seu nome: "))
idade = int (input("digite sua idade: "))

# Processamento - armazenar dados

# Saida - mensagem de boas vindas
print("------Bem vindo------")
print(f"Seu nome é: {nome}")
print(f"Sua idade é: {idade}")

# Entrada
print("------------ENTRADA DA TEMPERATURA------------")
celcius = float(input('digite a temperatura em graus celsius: '))

# Processamento
fahrenheit = (celcius * 9/5) + 32

# Saida
print('-------------CONVERSÃO------------')
print(f'A temperatura em fahrenheit é: {fahrenheit}')

"""Aula 04"""

from re import sub
# Operadora aritiméticos

# Entrada
a = int(input("digite o primeiro valor: "))
b = int(input("digite o segundo valor: "))

# Processamento

# Soma de dois números
soma = a + b
subtracao = a - b
multiplicacao = a * b
divisao = a / b
resto = a % b
# Saída
print('-------------SOMA------------')
print("")
print(f'A soma de {a} mais {b} é igual a: {soma}')
print("")
print('-------------SUBTRAÇÃO------------')
print("")
print(f"A subtração de {a} menos {b} é igual a: {subtracao}")
print("")
print('-------------MULTIPLICAÇÃO------------')
print("")
print(f"A multiplicação de {a} vezes {b} é igual a: {multiplicacao}")
print("")
print('-------------DIVISÃO------------')
print("")
print(f"A divisão de {a} por {b} é igual a: {divisao}")
print("")
print('-------------RESTO DA DIVISÃO------------')
print("")
print(f"O resto da divisão de {a} por {b} é: {resto}")
print("")

# Entrada
num1 = int(input("digite o primeiro numero: "))
num2 = int(input("digite o segundo numero: "))

#processamento

igual = num1 == num2
maior = num1 > num2
menor = num1 < num2
# Saída

print(igual)
print (maior)

# Escrever um programa que verefica se o usuário é maior de idade

nome = str(input("digite seu nome: "))
idade = int(input("digite sua idade: "))

if idade > 18:

   print (f"{nome} você é maior de idade")

else:

  print (f"nome: {nome} você é menor de idade")

# Escrever um programa que verifica se um número é par ou inpar
numero = int(input("Digite um número inteiro: "))

if numero % 2 == 0:
    print(f"O número {numero} é par.")
else:
    print(f"O número {numero} é ímpar.")

# Escrever um programa que verifica uma senha simples, senha -- 1234. saída de acesso permitido.
senha_correta = "1234"
senha_digitada = input("Digite a senha: ")

if senha_digitada == senha_correta:
    print("Acesso Permitido!")
else:
    print("Acesso Negado.")

# Escrever um programa que verifica se um número é maior que dez
numero = int(input("Digite um número: "))

if numero > 10:
    print(f"O número {numero} é maior que 10.")
else:
    print(f"O número {numero} não é maior que 10.")
#

# Escrever um programa que:
# Peça o valor da compra
# Se o valor for maior que 100, aplique um desconto de 10%
# Se não, mostre o valor normal.

valor_compra = float(input("Digite o valor da compra: "))

if valor_compra > 100:
    desconto = valor_compra * 0.10
    valor_final = valor_compra - desconto
    print(f"Valor com desconto (10%): R${valor_final:.2f}")
else:
    print(f"Valor normal: R${valor_compra:.2f}")

nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))
nota4 = float(input("Digite a quarta nota: "))

média = (nota1 + nota2 + nota3 + nota4) / 4

if média >= 7:

    print(f"Aluno Aprovado com média: {média:.2f}")

elif média > 5:

    print(f"Aluno em Recuperação: {média:.2f}")

else:

    print(f"Aluno Reprovado: {média:.2f}")

"""Aula 05"""

#Escrever um programa que realiza todas as operações aritimeticas

print("---------CALCULADORA SIMPLES--------")
print("")
print("----------------MENU----------------")
print("")
print("SOMA ----------------------------- 1")
print("")
print("SUBTRAÇÃO ------------------------ 2")
print("")
print("MULTIPLICAÇÃO -------------------- 3")
print("")
print("DIVISÃO -------------------------- 4")
print("------------------------------------")

esc = int(input("Digite a opção desejada: "))

if esc == 1:
    n1 = int(input("selecione o primeiro numero da soma: "))
    n2 = int(input("selecione o segundo numero da soma: "))
    calc = n1 + n2
    print(f"O resultado da Soma é: {calc}")

if esc == 2:
    n1 = int(input("selecione o primeiro numero da subtração:  "))
    n2 = int(input("selecione o segundo numero da subtração: "))
    calc = n1 - n2
    print(f"O resultado da Subtração é: {calc}")

if esc == 3:
    n1 = int(input("selecione o primeiro numero da multiplicação: "))
    n2 = int(input("selecione o segundo numero da multiplicação: "))
    calc = n1 * n2
    print(f"O resultad oda Multiplicação é: {calc}")

if esc == 4:
    n1 = int(input("selecione o primeiro numero da divisão: "))
    n2 = int(input("selecione o segundo numero da divisão: "))
    calc = n1 / n2
    print(f"O resultado da Divisão é: {calc}")

# Programa que classifica os tipos de triangulos:
#isoceles
#equilarero
#Escaleno

l1 = int(input("Digite o primeiro lado do triangulo: "))
l2 = int(input("Digite o segundo lado do triangulo: "))
l3 = int(input("Digite o terceiro lado do triangulo: "))

if l1 == l2 and l2 == l3:
    print("O triangulo é equilatero")

if l1 != l2 and l2 != l3 and l1 != l3:
    print("O triangulo é escaleno")

if (l1 == l2 or l2 == l3 or l1 == l3) and (l1 != l2 or l2 != l3 or l1 != l3):
    print("O triangulo é isoceles")